### ISSUE TITLE
Crear la base de QueEsticFent emprant GenApp

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/queesticfent#1]
Seguir
(1) Clonar la branca queesticfent-2.0 en un directori local
(2) Dins d'aquest directori seguir  les passes del video tutorial per crear la base del projecte QueEsticFent emprant GenApp (https://governdigital.fundaciobit.org/downloadsldap/videotutorial/2023_GENAPP/)
(3) Un cop es tenguin les taules generades es farà commit de l'executable de genapp

**Comment by fbosch-fundaciobit** [comment]
S'ha generat la base del projecte amb GenApp:

![image](https://github.com/Fundacio-Bit/queesticfent/assets/40387703/42201cbf-bc9a-43f6-9a2c-35696d2f564f)
