### ISSUE TITLE
Eliminar part pública de la WEB

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/queesticfent#10]
(1) Fer que directament quan un usuari accedeixi a queesticfent vagi a una zona autenticada per automàticament fer login.

(2) Per defecte un cop entrat a queesticfent, fer que vagi a Menú d'Usuari ennloc del Menú Inici.

**Comment by fbosch-fundaciobit** [comment]
Ja no hi ha manera d'arribar a la part pública. S'ha establert la pagina de benvinguda com a pagina inicial, i per tant un usuari no logejat es redirigit al formulari de login directament.

**Comment by anadal-fundaciobit** [comment]
No va a la pàgina de Llistat d'Entrades just quan acabes d'entrar ...

**Comment by fbosch-fundaciobit** [comment]
S'ha configurat la pagina de llistat d'entrades com la pàgina inicial.
