### ISSUE TITLE
Generar API Externa per donar d'alta entrades a QueEsticfent des de PinbalAdmin

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/queesticfent#12]
Generar API Externa per donar d'alta entrades a QueEsticfent des de PinbalAdmin

**Comment by fbosch-fundaciobit** [comment]
S'han generat els moduls d'API externa i API externa-client, amb la funció de ADD i una funció de test per aquesta funció.



![Image](https://github.com/Fundacio-Bit/queesticfent/assets/40387703/9d7969c0-1435-4514-afff-03709ada91b4)
