### ISSUE TITLE
Fer proves amb usuaris testuser i testadmin

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/queesticfent#15]
Fer proves amb els usuaris testuser i testadmin contra queesticfent.

**Comment by fbosch-fundaciobit** [comment]
S'han testejat els usuaris testuser i testadmin i s'han corregit tots els errors pertinents.

S'ha inclòs control d'errors i avisos en cas de que l'usuari no compti amb cap rol, o no estigui assignat a cap departament, i s'ha controlat que la pàgina inicial dels usuaris sigui l'apropiada segons els seus permisos:

Pàgina d'inici si no té departament o cap rol asignat.

Menú d'administrador si unicament té rol d'administrador.

Llistat d'entrades si té rol d'usuari i departament assignat.
