### ISSUE TITLE
Ignorar la taula de ProjectesPersones i mostrar a tothom tots els projectes

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/queesticfent#31]
Ignorar la taula de ProjectesPersones i mostrar a tothom tots els projectes.
En algun lloc del codi es filtren els projectes als quals té permis. Fer que tothom pugui veure tots els projectes.

**Comment by fbosch-fundaciobit** [comment]
Arreglat al Issue #42
