### ISSUE TITLE
Millores en la creació d'una Entrada

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/queesticfent#34]
(1) Canviar el títol per Nova Entrada (es fa emprant mètode getTitleCode())
(2) Arreglar tots el Labels excepte "Data"
(3) Convertit Data a tipus TimeStamp des de GenApp
(4) Ocultar camp Dada 2

![imatge](https://github.com/Fundacio-Bit/queesticfent/assets/17084256/e846055c-111b-4b23-82f0-905275f1389f)

**Comment by fbosch-fundaciobit** [comment]
S'han modificat els camps del formulari de creació d'una entrada.



![Image](https://github.com/Fundacio-Bit/queesticfent/assets/40387703/930127b6-7f75-4532-b134-0ded1a317b28)
