### ISSUE TITLE
Entrades ordenades per data o ID

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/queesticfent#35]
Les entrades afegides a un dia estan ordenades de forma aleatòria. Fer que s'ordenin per ID o Data i que apareguin segon s'han anat afegint durant el dia.

**Comment by fbosch-fundaciobit** [comment]
S'ha afegit ordenació a la llista d'items segons la hora introduida:



![Image](https://github.com/Fundacio-Bit/queesticfent/assets/40387703/77883d31-5fe6-4f47-90e6-751cbe66cdde)
