### ISSUE TITLE
Espai perdut en generació ODT

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/queesticfent#8]
Com s'observa en la imatge es pert molt d'espai abans i despres de cada paràgraf de cada dia. 
Revisar l'ODT per evitar aquesta pèdua d'espai.

![imatge](https://github.com/Fundacio-Bit/queesticfent/assets/17084256/e07e4808-511e-48de-8edb-2ab35b9b04e5)

**Comment by fbosch-fundaciobit** [comment]
S'han reduit els espais en blanc al minim:



![Image](https://github.com/Fundacio-Bit/queesticfent/assets/40387703/5ba22e31-34bc-42ab-874f-3ce4ab7cf49f)
