### ISSUE TITLE
Eliminar referències a org.apache.commons.lang

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/queesticfent#9]
Pareix que pel codi hi ha referències a la llibreria org.apache.commons.lang però no s'afegeix als jars ni del war ni de l'ear.

![imatge](https://github.com/Fundacio-Bit/queesticfent/assets/17084256/24ea91f5-ecc8-446a-8719-992834d17fe2)

(1) Eliminar les dependències a  org.apache.commons.lang (s'ha de comprovar des d'eclipse que ja no apareix la dependència ...)
(2) S'ha de mantenir la dependència a org.apache.commons.lang3
(3) S'ha d'afegir la dependència a commons-text per poder utilitzar la classe StringEscapeUtils sense avisos de deprecated:

![imatge](https://github.com/Fundacio-Bit/queesticfent/assets/17084256/d6cb63be-d33b-481a-a68a-72883843d0f6)

**Comment by fbosch-fundaciobit** [comment]
S'han canviat les dependències a commons.text
